config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :log_user_update_levels do
      member do
        patch :update_status
      end
    end
    
    resources :feedbacks, only: [:index] do
    end

    resources :users do
      collection do
        get :search
        get :contacted
        get :registered
        post :contact
        post :set_staff
        get :staff_list
      end
      member do
        get :edit_staff
        patch :update_staff
        get :update_remark
        get :update_status
        patch :update_role
        get :update_user_remark
      end
    end

    resources :banners
    resources :posts do
      collection do
        get :resources_list
        get :hot_resources
      end
      member do
        put :update_sys
        put :approve_base_car
      end
    end
    resources :helpers, except: [ :show ]

    resources :messages, only: [:index, :new, :create, :destroy]
    root 'users#search'
    resources :base_cars do
      member do
        get :update_status
      end
      collection do
        get :st_list
        get :br_list
        get :cm_list
        get :get_select_infos
        get :get_cm_select_infos
        get :new_cm
        get :new_br
        get :new_st
        get :edit_cm
        get :edit_br
        get :edit_st
        post :create_cm
        post :create_br
        post :create_st
        put :update_br
        put :update_st
        patch :update_cm
      end
    end
    resources :complaints, only: [:index, :update]
  end

  root 'portal#index'

  devise_for :users, controllers: {
                                    sessions:      'users/sessions',
                                    confirmations: 'users/confirmations',
                                    registrations: 'users/registrations',
                                    passwords:     'users/passwords',
                                    unlocks:       'users/unlocks'
                                  }

  namespace :users do
    resources :messages do
    end
  end

  resources :users, only: [ :show, :edit, :update ] do
    member do
      get :my_tenders
      get :my_followers
      get :system_infos
      get :my_level
      get :edit_my_level
      put :update_my_level
      get :about_us
    end
    patch :add_following, on: :collection

    get :delete_relation, on: :collection

    patch :reset_password, on: :collection

    get :user_protocel, on: :collection

    resources :my_posts do
      member do
        patch :update
      end
      collection do
        get :get_select_infos
        post :update_position
      end
      resources :tenders, only: [ :show ]
    end
  end

  resources :posts do
    collection do
      get :resources_list
      get :needs_list
      get :user_list
      get :user_resources_list
      get :download_posts
      get :key_search
    end
    member do
      post :tender
      put  :complete
      get  :my_tender
      get  :his_tender
    end
  end

  resources :follow_ships, only: [ :create, :destroy ]

  resources :valid_codes, only: [ :create ] do
    get :_valid, on: :collection
  end

  resources :photos, only: [ :index ] do
    post :upload, on: :collection
  end

  resources :areas, only: [:show]
  resources :complaints, only: [ :create ]
  resources :comments, only: [ :create ]

  resources :helpers, only: [ :index, :show ]

  resources :mobile_displays, only: [:index]

  namespace :api, :defaults => { :format => 'json' } do
    devise_scope :user do
      post    'sessions'      => 'sessions#create',       :as => 'login'
      delete  'sessions'      => 'sessions#destroy',      :as => 'logout'
      post    'registrations' => 'registrations#create',  :as => 'register'
    end

    resources :banners, only: [:index]
    resources :helpers, only: [ :index, :show ]

    resources :messages do
      post :device_methods, on: :collection
      post :update_messages, on: :collection
      post :destroy_messages, on: :collection
    end

    resources :base_cars, only: [:index]

    namespace :posts do
      get   :list
      get   :my_list
      get   :my_tenders
      get   :user_list
      get   :show
      post  :create
      post  :tender
      put   :complete
      post  :update_all
      put  :change_position
      delete :destroy
      put :del_my_tender
      get :search
      get :tender_status
      get :filter_brands
      get :filter_brand
      post :gen_log
    end

    resources :valid_codes, only: [:index] do
      get :validate_code, on: :collection
    end

    resources :areas, only: [:index] do
    end

    namespace :follow_ships do
      get   :my_followers
      get   :my_followings
      get   :joint_followers
      get   :joint_followings
      post  :create
      put   :unfollow
    end

    namespace :complaints do
      post :create
    end

    namespace :comments do
      get  :list
      post :create
      post :reply
    end

    namespace :users do
      get :list
      get :has_updated
      post :update_level
      patch :change_password
      patch :reset_password
      put   :update
      get :show
      get :check_unread
      get :customer_service
    end

    resources :phone_lists, only: [:index] do
      post :contact_list, on: :collection
      get :send_invite_message, on: :collection
    end
  end

  # mount RailsAdmin::Engine => '/a', as: 'rails_admin'

end

app/controllers/my_posts_controller.rb
# encoding: utf-8
class MyPostsController < BaseController
  before_filter :auth_my_self
  skip_before_filter :verify_authenticity_token


  def index
    @_type = params[:_type]
    @brand_id = params[:brand_id]
    unless @brand_id.blank?
      @posts = current_user.posts.mine.includes(:standard, :base_car, :car_model).joins(:brand).where("brands.id = #{@brand_id} and posts._type = #{@_type}").page(params[:page]).per(10)
    else
      @posts = current_user.posts.mine.includes(:standard, :base_car, :car_model).where(_type: @_type).page(params[:page]).per(10)
    end

    if params[:update_all]
      if current_user.could_update_my_resources?
        current_user.posts.resources.mine.update_all(updated_at: Time.now, expired_at: 7.days.since)
        current_user.gen_post_log(current_user.posts.resources.mine.first, 'update_all')
      else
        flash[:notice] = '对不起，您一个小时之内不能重复更新您的资源列表'
      end
    end

    @brands = current_user.posts.resources.includes(:brand).map(&:brand).uniq

    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def new
    # params[:_type] 资源类型 0 => 资源， 1 => 寻车
    @post = Post.new(_type: params[:_type])

    @standards  = Standard.all
    @standard   = Standard.first
    @brands     = @standard.brands.valid
    @brand      = @brands.first
    @car_models = CarModel.where(standard_id: @standards.first.id, brand_id: @brand.id, status: 1)
    @car_model  = @car_models.first
    @base_cars  = @car_model.base_cars.valid
    @base_car   = @base_cars.first
    @post_type  = @post._type
    @standard, @brand, @car_model, @base_car = *nil
  end

  def get_select_infos
    @post       = Post.new
    @post_type  = params[:post][:_type].to_i
    @standard   = Standard.find_by_id(params[:post][:standard_id])
    @brand      = Brand.find_by_id(params[:post][:brand_id])
    @car_model  = CarModel.find_by_id(params[:post][:car_model_id])
    @base_car   = BaseCar.find_by_id(params[:post][:base_car_id])

    @standards  = Standard.all
    @brands     = @standard.brands.valid
    @car_models = @brand ? CarModel.where(standard_id: @standard.id, brand_id: @brand.id, status: 1) : nil
    @base_cars  = @car_model ? @car_model.base_cars.valid : nil

    @car_model, @base_car = 'set_car_model', 'set_base_car' if  params[:post][:car_model_id]  == 'set_car_model'
    @base_car   = 'set_base_car' if params[:post][:base_car_id]  == 'set_base_car'

    render :partial => 'form_select'
  end

  def create
    standard  = Standard.find_by_id(params[:post][:standard_id])
    brand     = Brand.find_by_id(params[:post][:brand_id])
    car_model = CarModel.where(id: params[:post][:car_model_id], standard_id: standard.id, brand_id: brand.id).first
    base_car  = car_model ? BaseCar.where(standard_id: standard.id, brand_id: brand.id, id: params[:post][:base_car_id]).first : nil

    car_model = CarModel.create(
                  standard_id: standard.id,
                  brand_id: brand.id,
                  name: params[:post][:car_model_id],
                  status: 0
                ) unless car_model

    base_car  = BaseCar.create(
                  standard_id: standard.id,
                  brand_id: brand.id,
                  car_model_id: car_model.id,
                  style: params[:post][:base_car_id],
                  outer_color: [params[:post][:outer_color]],
                  inner_color: [params[:post][:inner_color]],
                  status: 0
                ) unless base_car

    # 为资源库保存自定义的颜色
    Log::BaseCar.create(
      user_id:      current_user.id,
      base_car_id:  base_car.id,
      method_name:  'outer_color',
      content:      params[:post][:outer_color]
    ) unless base_car.outer_color.include?(params[:post][:outer_color])

    Log::BaseCar.create(
      user_id:      current_user.id,
      base_car_id:  base_car.id,
      method_name:  'inner_color',
      content:      params[:post][:inner_color]
    ) unless base_car.inner_color.include?(params[:post][:inner_color])

    params.require(:post).permit!
    params[:post][:car_model_id] = car_model.id
    params[:post][:base_car_id]  = base_car.id

    photos = params[:post].delete(:post_photos)
    @post  = Post.new(params[:post])
    photos && photos.each do |k, v|
      @post.post_photos.new(_type: k, image: v.tempfile)
    end

    @post.user = current_user

    if @post.save
      redirect_to @post._type == 0 ? user_my_posts_path(current_user, _type: 0) : user_path(current_user)
    else
      render action: new, flash: @post.errors
    end
  end

  def edit
    @post       = Post.find_by_id(params[:id])
    @standards  = Standard.all
    @standard   = @post.standard
    @brands     = @standard.brands
    @brand      = @post.brand
    @car_models = CarModel.where(standard_id: @standard.id, brand_id: @brand.id)
    @car_model  = @post.car_model
    @base_cars  = @car_model.base_cars
    @base_car   = @post.base_car
    @post_type  = @post._type

    @discount_contents =  if @post.expect_price.to_f > @post.guiding_price.to_f
                            [nil, nil, (@post.expect_price.to_f - @post.guiding_price.to_f).round(2)]
                          else
                            [((@post.guiding_price.to_f - @post.expect_price.to_f)/@post.guiding_price.to_f*100).round(2), (@post.guiding_price.to_f - @post.expect_price.to_f).round(2), nil]
                          end
    @discount_contents << @post.expect_price
  end

  def update
    @post = Post.find_by_id(params[:id])
    standard  = Standard.find_by_id(params[:post][:standard_id])
    brand     = Brand.find_by_id(params[:post][:brand_id])
    car_model = CarModel.find_by_id(params[:post][:car_model_id])
    base_car  = BaseCar.find_by_id(params[:post][:base_car_id])

    # 为资源库保存自定义的颜色
    Log::BaseCar.create(
      user_id:      current_user.id,
      base_car_id:  base_car.id,
      method_name:  'outer_color',
      content:      params[:post][:outer_color]
    ) unless base_car.outer_color.include?(params[:post][:outer_color])

    Log::BaseCar.create(
      user_id:      current_user.id,
      base_car_id:  base_car.id,
      method_name:  'inner_color',
      content:      params[:post][:inner_color]
    ) unless base_car.inner_color.include?(params[:post][:inner_color])

    photos = params[:post].delete(:post_photos)
    params.require(:post).permit!
    @post.attributes = params[:post]
    photos && photos.each do |k, v|
      photo = @post.post_photos.find_by__type(k)
      if photo
        photo.update_attributes(image: v.tempfile)
      else
        @post.post_photos.new(_type: k, image: v.tempfile)
      end
    end

    if @post.save
      redirect_to user_my_posts_path(current_user, _type: 0)
    else
      render action: edit, flash: @post.errors
    end
  end

  def show
    @post = Post.find_by_id(params[:id])

    # LESLIE: 浏览该页面 意味着已查看了所有对该寻车的报价
    payload = { post_id: @post.id, method_name: 'tender' }
    instrument 'user.has_read_tender', payload
  end

  def destroy
    post  = Post.find_by_id(params[:id])

    post.update_attributes(status: -1)

    redirect_to user_path
  end

  # 更新post位置
  def update_position
    post = current_user.posts.resources.find params[:id]

    type = params[:type]
    swap_obj = current_user.posts.resources.find params[:swap_id]

    unless (type == 'down' and post.first?) or ( type == 'up' and post.last?)
      swap_tmp(post, swap_obj)
      post.save
      swap_obj.save
    end

    respond_to do |format|
      format.json {
        render nothing: true
      }
    end
    # render nothing
  end

  private

  def swap_tmp(objx, objy, temp=nil)
    temp = objx.position
    objx.position = objy.position
    objy.position = temp
  end

end

app/views/my_posts/_form_0.html.erb
<div class="panel panel-default contentBox">

  <div class="panel-heading lineTitle">
    <h3 class="panel-title"><%= @post.new_record? ? '发布资源' : '编辑资源' %></h3>
  </div>
  <div class="panel-body">
    <%- if @post.new_record? %>
        <%= form_tag(user_my_posts_path, method: :post, multipart: true, class: "form-horizontal sourceForm") do %>
            <%= render 'form_detail' %>
        <% end %>
    <% else %>
        <%= form_tag(user_my_post_path(current_user, @post), method: :put, multipart: true, class: "form-horizontal sourceForm") do %>
            <%= render 'form_detail' %>
        <% end %>
    <% end %></div>
</div>
<script type="text/javascript">
$(document).ready(function () {
  // $('#post_photos').find('input[type="file"]').on('change', function(){
  //   var n = $(this).attr('class').split(" ")[1];
  //   if(this.files && this.files[0]){
  //     var reader = new FileReader();
  //     reader.readAsDataURL(this.files[0]);
  //     reader.onload = function(e){
  //       $('.'+n).attr('src', e.target.result);
  //     };
  //   }
  // });
  $("#post_photo_front").uploadPreview({ Img: "post_front", Width: 140, Height: 94 });
  $("#post_photo_side").uploadPreview({ Img: "post_side", Width: 140, Height: 94 });
  $("#post_photo_obverse").uploadPreview({ Img: "post_obverse", Width: 140, Height: 94 });
  $("#post_photo_inner").uploadPreview({ Img: "post_inner", Width: 140, Height: 94 });
});
</script>

app/views/my_posts/_form_1.html.erb
<div class="panel panel-default contentBox">
  <div class="panel-heading lineTitle">
    <h3 class="panel-title">我要寻车</h3>
  </div>
  <div class="panel-body">
    <form class="form-horizontal sourceForm" action="<%= user_my_posts_path %>" method="post">
      <div id='form_select'>
        <%= render 'form_select' %>
      </div>
      <div class="sFormBox clearfix">
        <div class="sFormTag bfL">备注</div>
        <div class="sFormArea">
          <textarea class="form-control" rows="3" name="post[remark]"></textarea>
          <p class="txtTips">（可输入配置，手续时间，生产日期，现车期货等其他详细要求）</p>
        </div>
      </div>
      <div class="subGroup row">
        <input type="submit" class="btn btn-default orange btn_spacing" id="subBtn" value="发布" />
        <a href=<%= root_path %> class="btn btn-default btn_spacing">取消</a>
      </div>
    </form>
  </div>
</div>

app/views/my_posts/_form_select.html.erb
<div class="row first">
  <div class="form-group col-md-6">
    <label for="car_standard" class="col-md-4 control-label">规格</label>
    <div class="col-md-9 inputBox">
      <div class="dropdown w100p">
        <%- if @post.new_record? %>
          <select name="post[standard_id]" class="form-control input-sm" id="post_standard_id" datatype="*" data-url=<%= get_select_infos_user_my_posts_path(current_user.id)%>>
        <% else %>
          <select name="post[standard_id]" disabled class="form-control input-sm" id="post_standard_id" datatype="*" data-url=<%= get_select_infos_user_my_posts_path(current_user.id)%>>
        <% end %>
          <option value=''>请选择</option>
          <%- @standards.each do |standard| %>
            <%- if standard == @standard %>
              <option value="<%= standard.id %>" selected="selected"><%= standard[:name]%></option>
            <% else %>
              <option value="<%= standard.id %>"><%= standard[:name]%></option>
            <% end %>
          <% end %>
        </select>
      </div>
    </div>
  </div>
  <div class="form-group col-md-6">
    <label for="car_brand" class="col-md-4 control-label">品牌</label>
    <div class="col-md-9 inputBox">
      <div class="dropdown w100p">
        <%- if @post.new_record? %>
          <select name="post[brand_id]" class="form-control input-sm" id="post_brand_id" datatype="*" data-url=<%= get_select_infos_user_my_posts_path(current_user.id)%>>
        <% else %>
          <select name="post[brand_id]" disabled class="form-control input-sm" id="post_brand_id" datatype="*" data-url=<%= get_select_infos_user_my_posts_path(current_user.id)%>>
        <% end %>
          <option value=''>请选择</option>
          <%- @brands.group_by {|e| Pinyin.t(e.name)[0].upcase}.keys.sort.each do |letter| %>
            <%- @brands.group_by {|e| Pinyin.t(e.name)[0].upcase}[letter].each do |brand| %>
              <%- if brand == @brand %>
                <option value="<%= brand.id %>" selected="selected"><%= "#{letter}#{brand.name}" %></option>
              <% else %>
                <option value="<%= brand.id %>"><%= "#{letter}#{brand.name}" %></option>
              <% end %>
            <% end %>
          <% end %>
        </select>
      </div>
    </div>
  </div>
</div>
<input class='hide' id="post_type" name="post[_type]" value="<%= @post_type %>">
<%= render @car_model == 'set_car_model' ? 'car_model_input' : 'car_model_select'%>

<script type="text/javascript">
$(document).ready(function(){
  $('#post_standard_id').change(function(){
    if($(this).val()!=''){
      var url = $(this).data('url');
      var standard_id = $('#post_standard_id').val();
      var _type = $('#post_type').val();

      $.ajax({
        method: "GET",
        url: url,
        data: {
          post: {
            standard_id: standard_id,
            _type: _type
          }
        },
        success: function(data){$("#form_select").html(data)}
      });
    }
  });

  $('#post_brand_id').change(function(){
    if($(this).val()!=''){
      var url = $(this).data('url');
      var standard_id = $('#post_standard_id').val();
      var brand_id = $('#post_brand_id').val();
      var _type = $('#post_type').val();

      $.ajax({
        method: "GET",
        url: url,
        data: {
          post: {
            standard_id: standard_id,
            brand_id: brand_id,
            _type: _type
          }
        },
        success: function(data){$("#form_select").html(data)}
      });
    }
  });

  $('#post_car_model_id').change(function(){
    if($(this).val()!=''){
      var url = $(this).data('url');
      var standard_id = $('#post_standard_id').val();
      var brand_id = $('#post_brand_id').val();
      var car_model_id = $('#post_car_model_id').val();
      var _type = $('#post_type').val();

      $.ajax({
        method: "GET",
        url: url,
        data: {
          post: {
            standard_id: standard_id,
            brand_id: brand_id,
            car_model_id: car_model_id,
            _type: _type
          }
        },
        success: function(data){$("#form_select").html(data)}
      });
    }
  });

  $('#post_base_car_id').change(function(){
    if($(this).val()!=''){
      var url = $(this).data('url');
      var standard_id = $('#post_standard_id').val();
      var brand_id = $('#post_brand_id').val();
      var car_model_id = $('#post_car_model_id').val();
      var base_car_id = $('#post_base_car_id').val();
      var _type = $('#post_type').val();

      $.ajax({
        method: "GET",
        url: url,
        data: {
          post: {
            standard_id: standard_id,
            brand_id: brand_id,
            car_model_id: car_model_id,
            base_car_id: base_car_id,
            _type: _type
          }
        },
        success: function(data){$("#form_select").html(data)}
      });
    }
  });

  var offerGroup = $(".methodSelect").find(".form-group");
  var offerInput = $(".selectInput").find("input[type='text']");
  offerInput.attr("disabled", "true");
  offerGroup.find(".selectTag").each(function (e) {
      $(this).bind("click", function(){
          if ($(this).hasClass("disabled")) return false;
          offerGroup.find(".selectTag").removeClass("active");
          $(this).addClass("active");
          offerGroup.find(".selectInput").removeClass("active");
          $(this).next(".selectInput").addClass("active");
          offerGroup.find(".selectInput").find("input[type='text']").attr("disabled", "true");
          $(this).next(".selectInput").find("input[type='text']").removeAttr("disabled");
          $(this).next(".selectInput").find("input[type='text']").focus();
      });
  });
  var gPrice = parseFloat($("#guidePrice").html());
  if (isNaN(gPrice) || !gPrice || gPrice == "") {
      gPrice = 0;
      $("#methodVal1,#methodVal2,#methodVal3,#methodVal4").bind("focus blur keyup", function () {
          if ($(this).val() > 999) {
              $(this).val(999);
          }
      });
      $("#methodVal4").bind("focus blur keyup", function () {
          $("#methodVal1,#methodVal2,#methodVal3").val("");
      });
  }
  else {
      $("#methodVal1").bind("focus keyup", function(){
          if ($(this).val() > 100) {
              $("#methodVal1").val(100);
          }
          $("#methodVal2").val((gPrice * $(this).val() / 100).toFixed(2));
          $("#methodVal3").val(0);
          $("#methodVal4").val((gPrice - $("#methodVal2").val()).toFixed(2));
      });
      $("#methodVal2").bind("focus keyup", function(){
          $("#methodVal1").val(($(this).val() / gPrice * 100).toFixed(1));
          $("#methodVal3").val(0);
          if ($(this).val() > gPrice){
              $(this).val(gPrice);
              $("#methodVal4").val("");
          }
          else {
              $("#methodVal4").val((gPrice - $(this).val()).toFixed(2));
          }
      });
      $("#methodVal3").bind("focus keyup", function(){
          var thisV = parseFloat($(this).val());
          if (thisV > 999) {
              $(this).val(999);
          }
          else if (isNaN(thisV)) {
              thisV = 0;
          }
          $("#methodVal1,#methodVal2").val(0);
          $("#methodVal4").val((gPrice + thisV).toFixed(2));
      });

      $("#methodVal4").bind("focus keyup", function(){
          if ($(this).val() > 999) {
              $(this).val(999);
          }
          else if ($(this).val() < gPrice) {
              $("#methodVal2").val((gPrice - $(this).val()).toFixed(2));
              $("#methodVal1").val(($("#methodVal2").val() / gPrice * 100).toFixed(1));
              $("#methodVal3").val(0);
          }
          else {
              $("#methodVal1,#methodVal2").val(0);
              $("#methodVal3").val(($(this).val() - gPrice).toFixed(2));
          }
      });
  }
  $("#methodRadios5").click(function () {
      $(".selectInput").find("input.form-control").val("");
  });

  offerInput.each(function(){
      var thisVal = $(this).val();
      $(this).bind("click",function(){
          $(this).select();
      });
      $(this).bind("keyup",function(){
          clearNoNum(this);
      });
  });

  // 内饰外饰自定义
  $('body').on('change', '#car_appearance', function(){
    if ($(this).val() == "set_outer_color"){
      $('#car_appearance').parent().html('<input type="text" class="form-control input-sm" name="post[outer_color]" placeholder="输入不得超过8个字符" maxlength="8" datatype="*1-8" nullmsg="请填写外观！">')
    }
  });
  $('body').on('change', '#car_interior', function(){
    if ($(this).val() == "set_inner_color"){
      $('#car_interior').parent().html('<input type="text" class="form-control input-sm" name="post[inner_color]" placeholder="输入不得超过8个字符" maxlength="8" datatype="*1-8" nullmsg="请填写内饰！">')
    }
  });
});

function clearNoNum(obj){
  obj.value = obj.value.replace(/[^\d.]/g,""); //先把非数字的都替换掉，除了数字和.
  obj.value = obj.value.replace(/^\./g,""); //必须保证第一个为数字而不是.
  obj.value = obj.value.replace(/\.{2,}/g,"."); //保证只有出现一个.而没有多个.
  obj.value = obj.value.replace(".","$#$").replace(/\./g,"").replace("$#$","."); //保证.只出现一次，而不能出现两次以上
  obj.value = obj.value.replace(/^(\-)*(\d+)\.(\d\d).*$/,'$1$2.$3'); //只能输入两个小数
}
</script>

app/views/my_posts/_list_0.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to '首页', root_path %></li>
    <li class="active">我的资源</li>
  </ol>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-9 mainBox">
      <div class="panel panel-default contentBox">
        <div class="panel-heading lineTitle">
          <h3 class="panel-title">我的资源</h3>
        </div>
        <div class="panel-body">
          <div class="mySourceOpe clearfix">
            <div class="bfL">
              <a class="btn btn-default orange mr14" href="<%= new_user_my_post_path(current_user, _type: 0) %>" role="button">添加资源</a>
              <div class="btn-group">
                <%= select_tag 'brand', options_for_select(@brands.collect{|brand| [brand.name, brand.id]}, selected: @brand_id), class: 'form-control', id: 'brand_select', prompt:  '筛选(全部)', data_id: current_user.id -%>
              </div>
            </div>
            <div class="bfR">
            <%= form_tag user_my_posts_path(current_user), method: :get do %>
            <%= hidden_field_tag 'brand_id', @brand_id %>
            <%= hidden_field_tag '_type', @_type %>
            <%= hidden_field_tag 'update_all', 'true' %>
              <div class="updateTime mr20 bfL">最后更新时间：<span><%= @posts.first.try(:publish_time) %></span></div>
              <button class="btn btn-default bfR" type="submit"><span class="icon icon-refresh"></span>全部更新</button>
              <% end-%>

            </div>
          </div>
          <div class="mySourceTab mt10">
            <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
              <tbody>
                <% @posts.each do |post| %>
                  <tr data-id="<%= post.id%>">
                    <td>
                      <div class="box clearfix">
                        <div class="infoM">
                          <h5 class="name"><%= link_to post.title, post_path(post, _type: 0) %></h5>
                          <div class="info clearfix">
                            <div class="m"><%= post.standard_type %></div>
                            <div class="m"><%= post.color %></div>
                          </div>
                        </div>
                        <div class="infoPrice">
                          <p>
                            <span class="price"><%= post.show_price %></span>
                            <span class="time"><%= post.publish_time %></span>
                          </p>
                          <%- if post.base_car.is_valid? && post.base_car_base_price.to_f != 0.0 %>
                            <p>指导价：<%= post.base_price %></p>
                          <% end %>
                        </div>
                      </div>
                      <div class="remark clearfix">
                        <div class="tt bfL">备注：</div>
                        <div class="info"><%= post.remark %></div>
                      </div>
                      <div class="btnGroups">
                        <a class="btn btn-default btn-xs" href="<%= edit_user_my_post_path(current_user, post) %>" role="button">编辑</a>
                        <a class="btn btn-default btn-xs upBtn" href="javascript:;" role="button">上移</a>
                        <a class="btn btn-default btn-xs downBtn" href="javascript:;" role="button">下移</a>
                        <a class="btn btn-default btn-xs cancelBtn modalBtn" href="javascript:;" role="button" data-id="<%= post.id %>" data-type="posts" data-clazz="post" data-way="resources" data-toggle="modal" data-target="#alertModal">删除</a>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="pageList">
            <%= paginate @posts %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 mainRight">
      <%= render partial: 'partials/right_mine', locals: {hidden_button: false} %>
      <%= render partial: 'partials/right_search' %>
    </div>
  </div>
</div>

<%= render partial: 'users/del_modal' %>

app/views/my_posts/_list_1.html.erb
我的寻车

app/views/my_posts/_show_0.html.erb
<h1>我的资源详情</h1>

app/views/my_posts/index.html.erb
<%= render partial: "list_#{@_type}" %>

<%= content_for :footers do %>
  <%= javascript_include_tag 'resources', 'edit_user' %>
<% end %>

app/views/my_posts/show.html.erb
<%= render partial: "show_#{@post._type}" %>