config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :log_user_update_levels do
      member do
        patch :update_status
      end
    end
    
    resources :feedbacks, only: [:index] do
    end

    resources :users do
      collection do
        get :search
        get :contacted
        get :registered
        post :contact
        post :set_staff
        get :staff_list
      end
      member do
        get :edit_staff
        patch :update_staff
        get :update_remark
        get :update_status
        patch :update_role
        get :update_user_remark
      end
    end

    resources :banners
    resources :posts do
      collection do
        get :resources_list
        get :hot_resources
      end
      member do
        put :update_sys
        put :approve_base_car
      end
    end
    resources :helpers, except: [ :show ]

    resources :messages, only: [:index, :new, :create, :destroy]
    root 'users#search'
    resources :base_cars do
      member do
        get :update_status
      end
      collection do
        get :st_list
        get :br_list
        get :cm_list
        get :get_select_infos
        get :get_cm_select_infos
        get :new_cm
        get :new_br
        get :new_st
        get :edit_cm
        get :edit_br
        get :edit_st
        post :create_cm
        post :create_br
        post :create_st
        put :update_br
        put :update_st
        patch :update_cm
      end
    end
    resources :complaints, only: [:index, :update]
  end

  root 'portal#index'

  devise_for :users, controllers: {
                                    sessions:      'users/sessions',
                                    confirmations: 'users/confirmations',
                                    registrations: 'users/registrations',
                                    passwords:     'users/passwords',
                                    unlocks:       'users/unlocks'
                                  }

  namespace :users do
    resources :messages do
    end
  end

  resources :users, only: [ :show, :edit, :update ] do
    member do
      get :my_tenders
      get :my_followers
      get :system_infos
      get :my_level
      get :edit_my_level
      put :update_my_level
      get :about_us
    end
    patch :add_following, on: :collection

    get :delete_relation, on: :collection

    patch :reset_password, on: :collection

    get :user_protocel, on: :collection

    resources :my_posts do
      member do
        patch :update
      end
      collection do
        get :get_select_infos
        post :update_position
      end
      resources :tenders, only: [ :show ]
    end
  end

  resources :posts do
    collection do
      get :resources_list
      get :needs_list
      get :user_list
      get :user_resources_list
      get :download_posts
      get :key_search
    end
    member do
      post :tender
      put  :complete
      get  :my_tender
      get  :his_tender
    end
  end

  resources :follow_ships, only: [ :create, :destroy ]

  resources :valid_codes, only: [ :create ] do
    get :_valid, on: :collection
  end

  resources :photos, only: [ :index ] do
    post :upload, on: :collection
  end

  resources :areas, only: [:show]
  resources :complaints, only: [ :create ]
  resources :comments, only: [ :create ]

  resources :helpers, only: [ :index, :show ]

  resources :mobile_displays, only: [:index]

  namespace :api, :defaults => { :format => 'json' } do
    devise_scope :user do
      post    'sessions'      => 'sessions#create',       :as => 'login'
      delete  'sessions'      => 'sessions#destroy',      :as => 'logout'
      post    'registrations' => 'registrations#create',  :as => 'register'
    end

    resources :banners, only: [:index]
    resources :helpers, only: [ :index, :show ]

    resources :messages do
      post :device_methods, on: :collection
      post :update_messages, on: :collection
      post :destroy_messages, on: :collection
    end

    resources :base_cars, only: [:index]

    namespace :posts do
      get   :list
      get   :my_list
      get   :my_tenders
      get   :user_list
      get   :show
      post  :create
      post  :tender
      put   :complete
      post  :update_all
      put  :change_position
      delete :destroy
      put :del_my_tender
      get :search
      get :tender_status
      get :filter_brands
      get :filter_brand
      post :gen_log
    end

    resources :valid_codes, only: [:index] do
      get :validate_code, on: :collection
    end

    resources :areas, only: [:index] do
    end

    namespace :follow_ships do
      get   :my_followers
      get   :my_followings
      get   :joint_followers
      get   :joint_followings
      post  :create
      put   :unfollow
    end

    namespace :complaints do
      post :create
    end

    namespace :comments do
      get  :list
      post :create
      post :reply
    end

    namespace :users do
      get :list
      get :has_updated
      post :update_level
      patch :change_password
      patch :reset_password
      put   :update
      get :show
      get :check_unread
      get :customer_service
    end

    resources :phone_lists, only: [:index] do
      post :contact_list, on: :collection
      get :send_invite_message, on: :collection
    end
  end

  # mount RailsAdmin::Engine => '/a', as: 'rails_admin'

end

app/models/area.rb
# encoding: utf-8

class Area < ActiveRecord::Base
  
  #constants
  LEVELS = {
    province: 1,
    city: 2
  }
  
  has_many :users, class_name: 'User' # 和用户关联
  has_many :children, class_name: 'Area', foreign_key: :parent_id # 自关联
  belongs_to :parent, class_name: 'Area' # 自关联
  
  # scopes
  [:provinces, :cities].each { |a| scope a, -> { where(level: LEVELS[a.to_s.singularize.to_sym]) }}
  
  # instance_method
  #
  def as_api
    {
     id:       self.id,
     name:     self.name,
     level:    self.level
    }
  end
  
end

app/controllers/portal_controller.rb
# encoding: utf-8

# author: depp.yu
# 网站首页（目前是这个，如有需要，以后可以修改)

class PortalController < BaseController

  skip_before_action :authenticate_user!

  # 系统首页
  # 参数：
  def index
    @user = User.new unless current_user

    # 最热品牌，寻车6个，资源8个
    @need_brands = Brand.includes(:car_photo).where(name: APP_CONFIG['need_brands'].split(' '))
    # 寻车列表
    @needs      = Post.needs.valid.includes(:user, :car_model, :standard, :base_car, brand: [:car_photo]).order(created_at: :desc).limit(8)

    # 6个品牌对就的寻车列表
    @posts_with_brands = @need_brands.each_with_object({}) do |brand, ha|
                            posts = brand.posts.needs.valid.includes(:user, :car_model, :standard, :base_car).order(created_at: :desc).limit(8)
                            ha.merge!({brand.id => posts})
                            ha
                         end

    # 最热车源
    @hot_resources = Post.where(id: HotPost.all.map(&:post_id)).includes(:user, :standard, :brand, :car_model, :base_car, :post_photos).order(sys_set_count: :desc).limit(8)

    # 最新车源
    @resource_brands  = Brand.includes(:car_photo).where(name: APP_CONFIG['resource_brands'].split(' '))
    newest_resouces   = Post.resources.valid.includes(:user, :brand, :car_model, :base_car, :standard).order(updated_at: :desc).group_by(&:user_id)
    @newest_resouces  = []

    newest_resouces.each_with_index do |ele, i|
      break if i == 10
      @newest_resouces << ele.last.first
    end

    # 资源表
    # @user_posts = Post.resources.valid.select("DISTINCT on (user_id) *").order("updated_at desc")[0..9]
    @user_ids = Post.resources.valid.order(updated_at: :desc).map(&:user_id).uniq[0..9]
    @users = User.where("id" => @user_ids)

    @banners = Banner.use_web.order('banners.position')
  end

  # 首页搜索
  # 参数：
  #   channel: 搜索入口
  #   key: 关键字
  def search
    case params[:channel]
    when 'all' then

    when 'brand' then

    end
  end

end

app/helpers/portal_helper.rb
# encoding: utf-8

# author: depp.yu

module PortalHelper

  def all_brand
    # Brand.pluck(:name, :id)
    ary = []
    Brand.valid.group_by {|e| Pinyin.t(e.name)[0].upcase}.keys.sort.each do |letter|
      Brand.valid.group_by {|e| Pinyin.t(e.name)[0].upcase}[letter].each do |ele|
        ary << [letter + ele.name, ele.id]
      end
    end
    ary
  end

  # 选择省市
  def areas(opt = {})
    opt[:level] ||= 'provinces' # provinces, cities
    Area.send(opt[:level]).pluck(:name, :id)
  end

  def options_cities(province_id)
    Area.where(parent_id: province_id).collect {|c| [c.name, c.id]}
  end

  # post在首页的名称显示
  def post_name(post)
    t('find') << (post.base_car_to_human_name || ' ') << ' ' << t('sale') << post.car_license_areas
  end

end

app/views/portal/_hot_resources.html.erb
<div class="panel panel-default contentBox bgf9">
	<div class="panel-heading lineTitle">
		<h3 class="panel-title"><%= I18n.t('hot_resources') %></h3>
	</div>
	<div class="panel-body">
		<ul class="row hotCar">
			<%- @hot_resources.each do |post| %>
				<li class="col-md-3">
					<div class="thumbnail box">
						<a href="<%= post_path(post, {_type: 0}) %>" class="imgBox"><%= image_tag(post.photos[:front], alt: "", width: "100%")%></a>
						<div class="caption intro">
							<h5 class="name"><%= link_to post.title, post_path(post, {_type: 0}) %></h5>
							<p><%= post.standard_resource_type %></p>
							<p class="price"><%= post.show_price %></p>
							<p><%= post.user_company %></p>
						</div>
					</div>
				</li>
			<% end %>
		</ul>
		<div class="moreLink text-right"><%= link_to '更多 >>', posts_path(_type: 0) %></div>
	</div>
</div>

app/views/portal/_newest_resources.html.erb
<div class="panel panel-default contentBox">
	<div class="panel-heading lineTitle">
		<h3 class="panel-title"><%= t('new_resources') %></h3>
	</div>
	<div class="panel-body">
		<ul class="newSourceIcon clearfix">
			<%- @resource_brands.each do |brand| %>
				<li>
					<a href="<%= resources_list_posts_path(br: brand.id) %>">
						<p><%= image_tag(brand.car_photo.try(:image).try(:thumb), alt: "") %></p>
						<p><%= brand.name %></p>
					</a>
			</li>
			<% end %>
		</ul>
		<div class="sourceTab">
			<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
				<thead>
					<tr>
						<th width="34%">品牌/车型</th>
						<th width="12%">报价(万元)</th>
						<th width="14%">状态</th>
						<th width="18%">发布人</th>
						<th width="12%">资源表</th>
						<th width="10%">发布时间</th>
					</tr>
				</thead>
				<tbody>
					<%- @newest_resouces.each do |post| %>
					<tr>
						<td><%= link_to post.title, post_path(post, _type: 0), class: 'name' %></td>
						<td><span class="price"><%= post.show_price %></span></td>
						<td><%= post.standard_resource_type %></td>
						<td>
							<span><%= link_to post.owner, user_list_posts_path(user_id: post.user_id, _type: 0), class: 'name' %></span>
							<span class="tag"><%= image_tag(post.user_level_icon, alt: "", width: "40") if post.user.try(:is_show_icon?) %></span>
						</td>
						<td>
							<%= link_to '浏览', user_list_posts_path(user_id: post.user_id, _type: 0) %>
							<span class="sepLine">|</span>
							<%= link_to '下载', download_posts_posts_path(user_id: post.user_id) %>
						</td>
						<td><%= post.publish_time %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class="moreLink text-right"><%= link_to '更多 >>', posts_path(_type: 0) %></div>
	</div>
</div>

app/views/portal/_post_infos.html.erb
<div role="tabpanel" class="panel panel-default contentBox">
	<ul role="tablist" class="nav nav-tabs carInfoTabs">
		<li role="presentation" class="active"><a href="#allCarInfo"><%= t('post_info') %></a></li>
    <% @need_brands.each_with_index do |brand, i| %>
		  <li role="presentation"><a href="#carBrand<%= i + 1%>"><span class="icon"><%= image_tag(brand.car_photo.try(:image_path), alt: "")%></span><%= brand.name %></a></li>
	  <% end-%>
  </ul>

	<div class="panel-body">
		<div role="tabpanel" class="tab-pane active" id="allCarInfo">
			<ul class="carInfoList clearfix">
        <%- @needs.each do |post| %>
				<li>
					<div class="logo bfL"><%= image_tag(post.brand.car_photo.try(:image_path), alt: "") %></div>
					<div class="info">
						<h5 class="tt"><%= link_to post.need_title, post_path(post, {_type: 1}) %></h5>
						<p class="detail clearfix"><span class="bfL"><%= post.color %></span><span class="bfR"><%= post.owner_detail %></span></p>
					</div>
				</li>
				<% end -%>
			</ul>
		</div>

    <%- @posts_with_brands.each_with_index do |ele, index| %>
      <div role="tabpanel" class="tab-pane" id="carBrand<%= index+1 %>">
        <ul class="carInfoList clearfix">
          <% ele.last.each do |post| %>
            <li>
              <div class="logo bfL"><%= image_tag(post.brand.car_photo.try(:image_path), alt: "") %></div>
              <div class="info">
                <h5 class="tt"><%= link_to post.need_title, post_path(post, {_type: 1}) %></h5>
                <p class="clearfix"><span class="bfL"></span><%= post.color %><span class="bfR"><%= post.owner_detail %></span></p>
              </div>
            </li>
          <% end -%>
        </ul>
      </div>
    <% end %>

		<div class="moreLink text-right"><%= link_to '更多 >>', posts_path(_type: 1) %></div>
	</div>
</div>

app/views/portal/_resources.html.erb
<div role="tabpanel" class="panel panel-default contentBox">
	<div class="panel-heading lineTitle">
		<h3 class="panel-title"><%= t('resources_list') %></h3>
	</div>
	<div class="panel-body">
		<div class="sourceTab">
			<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
				<thead>
					<tr>
						<th width="16%">发布人</th>
						<th width="12%">注册地</th>
						<th width="50%">涉及品牌</th>
						<th width="12%">资源表</th>
						<th width="10%">发布时间</th>
					</tr>
				</thead>
				<tbody>
					<%- @user_ids.each do |u_id| %>
						<% user = @users.find_by_id(u_id) %>
						<tr>
							<td>
								<span><%= link_to user.heading_show, user_list_posts_path(user_id: user.id, _type: 0), class: 'name' %></span>
								<span class="tag"><%= image_tag(user.level_icon, alt: "", width: "40") if user.try(:is_show_icon?) %></span></td>
							<td><%= user.area_name %></td>
							<td><%= user.brands_ary %></td>
							<td>
								<%= link_to '浏览', user_list_posts_path(user_id: user.id, _type: 0) %>
								<span class="sepLine">|</span>
								<%= link_to '下载', download_posts_posts_path(user_id: user.id) %>
							</td>
							<td><%= user.posts.resources.order(updated_at: :desc).first.publish_time %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class="moreLink text-right"><%= link_to '更多 >>', user_resources_list_posts_path %></div>
	</div>
</div>

app/views/portal/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-9 mainBox">
			<div id="carousel-example-generic" class="banner mb10 carousel slide" data-ride="carousel">
			  <ol class="carousel-indicators">
          <% @banners.count.times do |i|%>

            <li data-target="#carousel-example-generic" data-slide-to="<%= i %>" class="<%= i == 0 ? 'active' : ''%>"></li>
          <%end-%>
			  </ol>

			  <div class="carousel-inner" role="listbox">
          <% @banners.each_with_index do |ban, i| %>
    			      <div class="<%= i== 0 ? 'item active' : 'item' %>">
    			      <a href="<%= ban.redirect_way || '#'%>" target="_blank"><%= image_tag(ban.image.url, alt: "", width: "100%")%></a>
    			    </div>
			    <%end%>
			  </div>

			  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			    <span class="sr-only">上一张</span>
			  </a>
			  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			    <span class="sr-only">下一张</span>
			  </a>
			</div>


			<%= render 'post_infos' %>
			<%= render 'hot_resources' %>
			<%= render 'newest_resources' %>
			<%= render 'resources' %>
		</div>
		<div class="col-md-3 mainRight">
			<%- if current_user %>
				<%= render partial: 'partials/right_mine', locals: {hidden_button: true} %>
			<% else %>
				<%= render partial: 'partials/right_login' %>
			<% end %>
			<%= render partial: 'partials/right_app_icon' %>
			<%= render partial: 'partials/right_search' %>
			<%= render partial: 'partials/right_history_list' if current_user %>
		</div>
	</div>
</div>

<%= content_for :footers do %>
  <%= javascript_include_tag 'portal', 'data-turbolinks-track' => true %>
<% end -%>