config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :log_user_update_levels do
      member do
        patch :update_status
      end
    end
    
    resources :feedbacks, only: [:index] do
    end

    resources :users do
      collection do
        get :search
        get :contacted
        get :registered
        post :contact
        post :set_staff
        get :staff_list
      end
      member do
        get :edit_staff
        patch :update_staff
        get :update_remark
        get :update_status
        patch :update_role
        get :update_user_remark
      end
    end

    resources :banners
    resources :posts do
      collection do
        get :resources_list
        get :hot_resources
      end
      member do
        put :update_sys
        put :approve_base_car
      end
    end
    resources :helpers, except: [ :show ]

    resources :messages, only: [:index, :new, :create, :destroy]
    root 'users#search'
    resources :base_cars do
      member do
        get :update_status
      end
      collection do
        get :st_list
        get :br_list
        get :cm_list
        get :get_select_infos
        get :get_cm_select_infos
        get :new_cm
        get :new_br
        get :new_st
        get :edit_cm
        get :edit_br
        get :edit_st
        post :create_cm
        post :create_br
        post :create_st
        put :update_br
        put :update_st
        patch :update_cm
      end
    end
    resources :complaints, only: [:index, :update]
  end

  root 'portal#index'

  devise_for :users, controllers: {
                                    sessions:      'users/sessions',
                                    confirmations: 'users/confirmations',
                                    registrations: 'users/registrations',
                                    passwords:     'users/passwords',
                                    unlocks:       'users/unlocks'
                                  }

  namespace :users do
    resources :messages do
    end
  end

  resources :users, only: [ :show, :edit, :update ] do
    member do
      get :my_tenders
      get :my_followers
      get :system_infos
      get :my_level
      get :edit_my_level
      put :update_my_level
      get :about_us
    end
    patch :add_following, on: :collection

    get :delete_relation, on: :collection

    patch :reset_password, on: :collection

    get :user_protocel, on: :collection

    resources :my_posts do
      member do
        patch :update
      end
      collection do
        get :get_select_infos
        post :update_position
      end
      resources :tenders, only: [ :show ]
    end
  end

  resources :posts do
    collection do
      get :resources_list
      get :needs_list
      get :user_list
      get :user_resources_list
      get :download_posts
      get :key_search
    end
    member do
      post :tender
      put  :complete
      get  :my_tender
      get  :his_tender
    end
  end

  resources :follow_ships, only: [ :create, :destroy ]

  resources :valid_codes, only: [ :create ] do
    get :_valid, on: :collection
  end

  resources :photos, only: [ :index ] do
    post :upload, on: :collection
  end

  resources :areas, only: [:show]
  resources :complaints, only: [ :create ]
  resources :comments, only: [ :create ]

  resources :helpers, only: [ :index, :show ]

  resources :mobile_displays, only: [:index]

  namespace :api, :defaults => { :format => 'json' } do
    devise_scope :user do
      post    'sessions'      => 'sessions#create',       :as => 'login'
      delete  'sessions'      => 'sessions#destroy',      :as => 'logout'
      post    'registrations' => 'registrations#create',  :as => 'register'
    end

    resources :banners, only: [:index]
    resources :helpers, only: [ :index, :show ]

    resources :messages do
      post :device_methods, on: :collection
      post :update_messages, on: :collection
      post :destroy_messages, on: :collection
    end

    resources :base_cars, only: [:index]

    namespace :posts do
      get   :list
      get   :my_list
      get   :my_tenders
      get   :user_list
      get   :show
      post  :create
      post  :tender
      put   :complete
      post  :update_all
      put  :change_position
      delete :destroy
      put :del_my_tender
      get :search
      get :tender_status
      get :filter_brands
      get :filter_brand
      post :gen_log
    end

    resources :valid_codes, only: [:index] do
      get :validate_code, on: :collection
    end

    resources :areas, only: [:index] do
    end

    namespace :follow_ships do
      get   :my_followers
      get   :my_followings
      get   :joint_followers
      get   :joint_followings
      post  :create
      put   :unfollow
    end

    namespace :complaints do
      post :create
    end

    namespace :comments do
      get  :list
      post :create
      post :reply
    end

    namespace :users do
      get :list
      get :has_updated
      post :update_level
      patch :change_password
      patch :reset_password
      put   :update
      get :show
      get :check_unread
      get :customer_service
    end

    resources :phone_lists, only: [:index] do
      post :contact_list, on: :collection
      get :send_invite_message, on: :collection
    end
  end

  # mount RailsAdmin::Engine => '/a', as: 'rails_admin'

end

app/controllers/admin/posts_controller.rb
# encoding: utf-8
class Admin::PostsController < Admin::BaseController
  before_filter :require_super_admin, except: [:resources_list, :update_sys, :hot_resources]

  def index
    unvalid_bc_ids = BaseCar.unvalid.map(&:id)
    @posts = Post.valid.where(base_car_id: unvalid_bc_ids).includes(:user, :standard, :brand, :car_model, :base_car).order('created_at desc').page(params[:page]||1).per(30)
  end

  def destroy
    @post = Post.find_by_id(params[:id])

    @post.update_attributes(status: -1)

    redirect_to :back
  end

  def approve_base_car
    ele = params[:resource_type].classify.constantize.find_by_id(params[:resource_id])

    ele.update_attributes(status: 1)

    redirect_to :back
  end

  def resources_list
    @posts = Post.resources.valid.includes(:user, :standard, :brand, :car_model, :base_car).order('updated_at desc').page(params[:page]||1).per(30)
  end

  def update_sys
    post = Post.find_by_id(params[:id])
    post.update_attributes(sys_set_count: Post.valid.resources.map(&:sys_set_count).max.succ)

    redirect_to :back
  end

  # 限八个
  def hot_resources
    params[:post_ids] && params[:post_ids].each do |k, v|
      hot_post = HotPost.find_by_id(k)
      hot_post.update_attributes(post_id: v) if hot_post
    end
    @hot_posts = HotPost.includes(post: [:user, :standard, :brand, :car_model, :base_car]).order('created_at asc')
  end

end

app/controllers/api/posts_controller.rb
# encoding: utf-8
# 市场资源，寻车信息
require_relative '../../../app/services/query_posts'
class Api::PostsController < Api::BaseController

  # 市场资源列表，寻车列表
  #
  # Params:
  #   token:        [String]    valid token
  #   _type:        [Integer]   0 资源 1 寻车
  #   page:         [Integer]   页码 # 从0开始
  #   per:          [Integer]   每页记录数
  #
  # Return:
  #   status: [Integer] 200
  #   notice: [String]  success
  #   data:   [JSON]    posts json
  # Error
  #   status: [Integer] 400
  #   Notice: [String]  请重新再试
  def list
    conds = {_type: params[:_type]}

    page = params[:page] ? params[:page] : 1
    per  = params[:per]  ? params[:per]  : 10
    posts = Post.valid.where(conds).order(created_at: :desc).page(page).per(per)

    data = posts.map { |post| post.to_hash.merge!( is_following: @user.following?(post.user) ) }
    render json: {status: 200, notice: 'success', data: { posts: data } }
  end

  # 我的资源列表，寻车列表
  #
  # Params:
  #   token:        [String]    valid token
  #   _type:        [Integer]   0 资源 1 寻车
  #
  #
  # Return:
  #   status: [Integer] 200
  #   notice: [String]  success
  #   data:   [JSON]    my_posts json
  # Error
  #   status: [Integer] 400
  #   Notice: [String]  请重新再试
  def my_list

    posts = @user.posts.mine.where(_type: params[:_type]).order(updated_at: :desc)

    if params[:_type] == '1' # 仅针对寻车
      instrument 'user.has_read_tender', post_id: posts.pluck(:id)
    end

    render json: {status: 200, notice: 'success', data: {posts: posts.map(&:to_hash)}}
  end

  # 我的报价列表
  #
  # Params:
  #   token:        [String]    valid token
  #   page:         [Integer]   页码 # 从0开始
  #   per:          [Integer]   每页记录数
  #
  #
  # Return:
  #   status: [Integer] 200
  #   notice: [String]  success
  #   data:   [JSON]    uncompleted and completed json
  # Error
  #   status: [Integer] 400
  #   Notice: [String]  请重新再试
  def my_tenders
    page = params[:page] ? params[:page] : 1
    per  = params[:per]  ? params[:per]  : 10

    u_c = @user.tenders.completed
    uncompleted = @user.tenders.uncompleted.order(updated_at: :desc).page(page).per(per).map(&:to_hash)
    completed   = u_c.order(updated_at: :desc).page(page).per(per).map(&:to_hash)

    post_ids = u_c.pluck(:post_id)
    instrument 'user.has_read_hunt', post_id: post_ids, user_id: @user.id do
      render json: {status: 200, notice: 'success', data: {uncompleted: uncompleted, completed: completed}}
    end

    rescue => e
    render json: {status: false, error: e.message}
  end

  # 他的资源列表，寻车列表
  #
  # Params:
  #   token:        [String]    valid token
  #   user_id:      [Integer]   user ID
  #   _type:        [Integer]   0 资源 1 寻车
  #   page:         [Integer]   页码 # 从0开始
  #   per:          [Integer]   每页记录数
  #
  #
  # Return:
  #   status: [Integer] 200
  #   notice: [String]  success
  #   data:   [JSON]    his_posts json
  # Error
  #   status: [Integer] 400
  #   Notice: [String]  请重新再试
  def user_list
    user = User.find_by_id(params[:user_id])

    raise 'not found' unless user

    page = params[:page] ? params[:page] : 1
    per  = params[:per]  ? params[:per]  : 10

    posts = user.posts.where(_type: params[:_type]).page(page).per(per)

    render json: {status: 200, notice: 'success', data: {posts: posts.map(&:to_hash)}}

    rescue => e
    render json: {status: false, error: e.message}
  end

  # 单独的资源，寻车
  #
  # Params:
  #   token: [String]  valid token
  #   _type: [Integer] 0|1
  #   id   : [Integer] post ID
  #
  # Return:
  #   status: [Integer] 200
  #   notice: [String]  success
  #   data:   [JSON]    post json
  # Error
  #   status: [Integer] 400
  #   Notice: [String]  请重新再试
  def show
    type = params[:_type]
    post = Post.find_by_id(params[:id])
    if post
      render json: {status: 200, data: {post: post.to_hash}}
    else
      render json: {status: 200, notice: 'not_found', data: {}}
    end
  end

  # 创建资源或寻车
  #
  # Params:
  #   token:                    [String]      valid token
  #   post[_type]:              [Integer]     类型 0 资源 1 寻车
  #   post[resource_type]:      [Integer]     资源类型(只有资源有) 0 现车 1 期货
  #   post[standard_id]:        [Integer]     规格 ID select
  #   post[brand_id]:           [Integer]     品牌 ID select
  #   post[car_model_id]:       [Integer]     车型
  #   post[outer_color]:        [String]      外观颜色
  #   post[inner_color]:        [String]      内饰颜色
  #   post[base_car_id]:        [Integer]     基本库 ID 匹配
  #   post[car_license_area]:   [String]      上牌区域
  #   post[car_in_area]:        [Array]       车辆所在地
  #   post[take_car_date]:      [Integer]     提车日期 select
  #   post[discount_way]:       [Integer]     出价方式(电议只有资源有) select
  #   post[discount_content]:   [Float]       出价详情
  #   post[post_photos]:        [File Array]  资源图片
  #   post[remark]:             [String]      备注
  #
  # Return:
  #   status: [Integer] 200
  #   notice: [String]  success
  #   data:   [JSON]    post attrs
  # Error
  #   status: [Integer] 400
  #   Notice: [String]  failure
  #   data:   [JSON]    post errors
  def create
    params.require(:post).permit!

    post      = Post.find_or_initialize_by(id: params[:post][:id])
    standard  = Standard.find_by_id(params[:post][:standard_id])
    brand     = Brand.find_by_id(params[:post][:brand_id])
    car_model = CarModel.where(id: params[:post][:car_model_id], standard_id: standard.id, brand_id: brand.id).first
    base_car  = car_model ? BaseCar.where(standard_id: standard.id, brand_id: brand.id, id: params[:post][:base_car_id]).first : nil

    car_model = CarModel.create(
                  standard_id:  standard.id,
                  brand_id:     brand.id,
                  name:         params[:post][:car_model_id],
                  status:       0
                ) unless car_model

    base_car  = BaseCar.create(
                  standard_id:  standard.id,
                  brand_id:     brand.id,
                  car_model_id: car_model.id,
                  style:        params[:post][:base_car_id],
                  outer_color:  [params[:post][:outer_color]],
                  inner_color:  [params[:post][:inner_color]],
                  status: 0
                ) unless base_car

    params[:post][:car_model_id] = car_model.id
    params[:post][:base_car_id]  = base_car.id

    # 为资源库保存自定义的颜色
    Log::BaseCar.create(
      user_id:      current_user.id,
      base_car_id:  base_car.id,
      method_name:  'outer_color',
      content:      params[:post][:outer_color]
    ) unless base_car.outer_color.include?(params[:post][:outer_color])

    Log::BaseCar.create(
      user_id:      current_user.id,
      base_car_id:  base_car.id,
      method_name:  'inner_color',
      content:      params[:post][:inner_color]
    ) unless base_car.inner_color.include?(params[:post][:inner_color])

    photos = {}
    aa = params[:post].delete(:post_photos)
    aa && aa.each do |ele|
      photos[ele['_type']] = params.delete(ele['_type'])
    end
    post.attributes = params[:post]
    # 资源传图
    photos && photos.each do |k, v|
      if v
        post.post_photos.new(_type: k, image: v.tempfile)
      else
        post.post_photos.where(_type: k).delete_all
      end
    end

    post.user = @user

    if post.save
      render json: {status: 200, notice: 'success', data: {post: post.to_hash}}
    else
      render json: {status: 400, notice: 'failure', data: {errors: post.errors}}
    end
  rescue => e
    render json: {status: 400, notice: 'failure', data: {errors: e.errors}}
  end

  # 报价
  #
  # Params:
  #   token:                     [String]    valid token
  #   tender[post_id]:           [Integer]   post ID
  #   tender[discount_way]:      [Integer]   报价方式
  #   tender[discount_content]:  [Float]     报价详情
  #   tender[remark]:            [String]    备注
  #
  # Return:
  #   status: [Integer] 200
  #   notice: [String]  success
  # Error
  #   status: [Integer] 400
  #   Notice: [String]  请重新再试
  def tender
    post = Post.find_by_id_and__type(params[:tender][:post_id], 1)

    raise 'not found' unless post

    params.require(:tender).permit!
    tender = Tender.new(params[:tender].merge(user_id: @user.id))

    if tender.save
      render json: {status: 200, notice: 'success', data: {tender: tender}}
    else
      render json: {status: 400, notice: 'failure'}
    end

  rescue => e
    render json: {status: false, error: e.message}
  end

  # 成交寻车
  #
  # Params:
  #   token:    [String]    valid token
  #   post_id:  [Integer]   post ID
  #   tender_id:[Integer]   tender ID
  #
  # Return:
  #   status: [Integer] 200
  #   notice: [String]  success
  # Error
  #   status: [Integer] 400
  #   Notice: [String]  请重新再试
  def complete
    post = @user.posts.needs.find_by_id(params[:post_id])

    raise 'not found' unless post

    tender = post.tenders.find_by_id(params[:tender_id])

    raise 'not found' unless tender

    post.complete(tender.id)

    render json: {status: 200, notice: 'success', data: {post: post, tender: tender}}
  end

  # 撤销我的报价
  #
  # Params:
  #   token:    [String]    valid token
  #   id:       [Integer]   tender ID
  #
  # Return:
  #   status: [Integer] 200
  #   notice: [String]  success
  # Error
  #   status: [Integer] 400
  #   Notice: [String]  请重新再试
  def del_my_tender
    tender = Tender.find_by_id(params[:id])

    raise 'not found' unless tender
    raise 'you have no right to do it!' unless tender.user == @user

    tender.update_attributes(status: -1)


    render json: {status: 200, notice: 'success'}
    rescue => e
    render json: {status: false, error: e.message}
  end

  # 资源更新
  #
  # Params:
  #   token:    [String]    valid token
  #   post_ids: [Array]     资源的id
  # Return:
  #   status: [Integer] 200
  #   notice: [String]  success
  # Error
  #   status: [Integer] 500
  #   notice: [String]  failed
  #   error_msg: 错误信息

  def update_all
    if @user.could_update_my_resources?
      posts = @user.posts.resources.where("id in (?)", params[:post_ids])

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/post_helper.rb
# encoding: utf-8

module PostHelper

  def following?(user)
    current_user && current_user.following?(user) ? '已关注' : ''
  end

  def resource_name(post)
    "#{post.brand_name} #{post.car_model_name} #{post.base_car_NO}"
  end
end

app/views/posts/_form_detail.html.erb
<div id='form_select'>
  <%= render 'form_select' %>
</div>
<div class="sFormBox clearfix">
  <div class="sFormTag bfL">照片</div>
  <ul class="row first sFormArea addImgGroups" id="post_photos">
    <%- Post::PHOTOS.each do |k, v| %>
        <li class="col-md-3">
          <div class="thumbnail box">
            <div class="img" id=<%= k %>>
              <span class="alt"><%= v %></span><%= image_tag(@post.photos[k], alt: "", width: "100%", id: "post_#{k}") %></div>
            <div class="fileInput">
              <div class="fileBtn">添加照片<input type="file" class="button <%= k %>" name=<%= "post[post_photos][#{k}]" %> id="<%= "post_photo_#{k}"%>"/>
              </div>
            </div>
          </div>
        </li>
    <% end %>
  </ul>
</div>
<div class="sFormBox mt-20 clearfix">
  <div class="sFormTag bfL">备注</div>
  <div class="sFormArea">
    <textarea class="form-control" rows="3" name="post[remark]"><%= @post.remark %></textarea>
    <p class="txtTips">（可输入选装配置，提车要求，手续时间等其他详细信息）</p>
  </div>
</div>
<div class="subGroup row">
  <input type="submit" id="subBtn" class="btn btn-default orange btn_spacing" value="<%= @post.new_record? ? '发布' : '提交'%>"/>
  <a href=<%= user_list_posts_path(user_id: @someone.id, _type: 0) %> class="btn btn-default btn_spacing">取消</a>
</div>

app/views/posts/_list_0.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "首页", root_path %></li>
    <li class="active">市场资源</li>
  </ol>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-9 mainBox">
      <div class="panel panel-default contentBox">
        <div class="panel-heading lineTitle">
          <h3 class="panel-title">热门品牌/车型</h3>
        </div>
        <div class="panel-body souSelList">
          <div class="carList clearfix">
            <div class="tt">规格：</div>
            <div class="listBox">
              <ul class="list clearfix">
                <li><%= link_to '全部', resources_list_posts_path %></li>
                <%- @standards.each do |sd| %>
                  <li><%= link_to sd.name, resources_list_posts_path(st: sd.id) %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="carList clearfix">
            <div class="tt">品牌：</div>
            <div class="listBox">
              <ul class="list clearfix">
                <%- @brands.each do |br| %>
                  <li><%= link_to br.name, resources_list_posts_path(br: br.id) %></li>
                <% end %>
              </ul>
              <p class="txtR"><%= link_to '[更多]', resources_list_posts_path, class: 'moreLink' %></p>
            </div>
          </div>
          <div class="carList last clearfix">
            <div class="tt">车型：</div>
            <div class="listBox">
              <ul class="list clearfix">
                <%- @car_models.each do |cm|%>
                  <li><%= link_to cm.name, resources_list_posts_path(cm: cm.id) %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default contentBox">
        <div class="panel-heading lineTitle">
          <h3 class="panel-title">全部资源（<%= @posts.total_count %>）</h3>
        </div>
        <div class="panel-body">
          <div class="mySourceTab mt10">
      <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
        <tbody>
        <%- @posts.each do |post| %>
            <tr>
              <td>
                <div class="box clearfix">
                  <div class="infoM">
                    <h5 class="name"><%= link_to post.title, post_path(post, {_type: 0}) %></a></h5>

                    <div class="info clearfix">
                      <div class="m"><%= post.st_rt %></div>
                      <div class="m"><%= post.color %></div>
                      <div class="m">
                        <span class="tag"><%= image_tag(post.user_level_icon, alt: "", width: "100%") if post.user.try(:is_show_icon?) %></span><span><%= link_to post.owner, user_list_posts_path(user_id: post.user_id, _type: 0) %></span><span class="statu"><%= following?(post.user) %></span>
                      </div>
                    </div>
                  </div>
                  <div class="infoPrice">
                    <p>
                      <span class="price"><%= post.show_price %></span>
                      <span class="time"><%= post.publish_time %></span>
                    </p>
                    <%- if post.base_car.is_valid? && post.base_car_base_price.to_f != 0.0 %>
                      <p>指导价：<%= post.base_price %></p>
                    <% end %>
                  </div>
                </div>
                <div class="remark clearfix">
                  <div class="tt bfL">备注：</div>
                  <div class="info"><%= post.remark %></div>
                </div>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="pageList">
      <%= paginate @posts %>
    </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 mainRight">
      <%= render partial: 'partials/right_mine', locals: {hidden_button: true} %>
      <%= render partial: 'partials/right_search' %>
      <%= render partial: 'partials/right_history_list' %>
    </div>
  </div>
</div>

app/views/posts/_list_1.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><%= link_to "首页", root_path %></li>
    <li class="active">寻车信息</li>
  </ol>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-9 mainBox">
      <div class="panel panel-default contentBox">
        <div class="panel-heading lineTitle">
          <h3 class="panel-title">寻车信息筛选</h3>
        </div>
        <div class="panel-body souSelList">
          <div class="carList clearfix">
            <div class="tt">规格：</div>
            <div class="listBox">
              <ul class="list clearfix">
                <li><%= link_to '全部', needs_list_posts_path %></li>
                <%- @standards.each do |sd| %>
                  <li><%= link_to sd.name, needs_list_posts_path(st: sd.id) %></li>
                <% end %>
              </ul>
            </div>
          </div>
          <div class="carList clearfix">
            <div class="tt">品牌：</div>
            <div class="listBox">
              <ul class="list clearfix">
                <%- @brands.each do |br| %>
                  <li><%= link_to br.name, needs_list_posts_path(br: br.id) %></li>
                <% end %>
              </ul>
              <p class="txtR"><%= link_to '[更多]', needs_list_posts_path, class: 'moreLink' %></p>
            </div>
          </div>
          <div class="carList last clearfix">
            <div class="tt">车型：</div>
            <div class="listBox">
              <ul class="list clearfix">
                <%- @car_models.each do |cm|%>
                  <li><%= link_to cm.name, needs_list_posts_path(cm: cm.id) %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="panel panel-default contentBox">
        <div class="panel-heading lineTitle">
          <h3 class="panel-title">全部寻车（<%= @posts.total_count %>）</h3>
        </div>
        <div class="panel-body">
          <div class="sourceTab">
            <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped">
              <thead>
                <tr>
                  <th width="30%">品牌/车型</th>
                  <th width="10%">上牌地点</th>
                  <th width="26%">外观/内饰</th>
                  <th width="24%">发布人</th>
                  <th width="10%">发布时间</th>
                </tr>
              </thead>
              <tbody>
                <%- @posts.each do |post| %>
                  <tr>
                    <td><%= link_to post.title, post_path(post.id, _type: 1)%></td>
                    <td><%= post.car_license_area %></td>
                    <td><%= post.color %></td>
                    <td><%= post.owner %></td>
                    <td><%= post.publish_time %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="pageList">
            <%= paginate @posts %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-3 mainRight">
      <%= render partial: 'partials/right_mine', locals: {hidden_button: true} %>
      <%= render partial: 'partials/right_search' %>
    </div>
  </div>
</div>

app/views/posts/_resource_select.html.erb
<div class="row">
  <div class="form-group col-md-6">
    <label for="car_status" class="col-md-4 control-label">状态</label>
    <div class="col-md-9 inputBox">
      <div class="dropdown w100p">
        <select name="post[resource_type]" class="form-control input-sm" id="car_date">
          <%- Post::RESOURCE_TYPE.each do |k, v|%>
            <% next if k == -1 %>
            <%- if @post && @post.resource_type == k %>
              <option value="<%= k %>"selected="selected"><%= v %></option>
            <% else %>
              <option value="<%= k %>"><%= v %></option>
            <% end %>
          <% end %>
        </select>
      </div>
    </div>
  </div>
</div>

app/views/posts/_sub_comment.html.erb
<% sub_comms.each_with_index do |c, i| %>
  <% if i == comm_counts + 1 %>
    <li class="last">
      <div class="photo bfL"><a href="#"><%= image_tag(c.user.avatar, alt: "", size: '45x45')%></a></div>
      <div class="detail">
        <div class="info"><span class="name"><a href="#"><%= c.user_name%>：</a></span><%= c.content %></div>
        <div class="time"><a href="#new_comment" class="icon icon-message"></a><%= human_time(c.updated_at) %></div>
      </div>
    </li>
  <% else %>
    <li>
      <div class="photo bfL"><a href="#"><%= image_tag(c.user.avatar, alt: "", size: '45x45')%></a></div>
      <div class="detail">
        <div class="info"><span class="name"><a href="#"><%= c.user_name%>：</a></span><%= c.content %></div>
        <div class="time"><a href="#new_comment" class="icon icon-message" data-name="<%= c.user_name %>" data-parent-id="<%= c.id %>"></a><%= human_time(c.updated_at) %></div>
      </div>
    </li>
  <% end -%>
  
<%end-%>

app/views/posts/_tender_info.html.erb
<div class="detailPriceInfo row">
  <div class="info bfL">
    <p class="price"><%= current_user == @post.user ? '他的报价' : '我的报价' %>：<span class="num"><%= @tender.price %>万</span></p>
    <%- if @post.base_car.is_valid? && @post.base_car_base_price.to_f != 0.0 %>
      <p>指导价：<%= @tender.base_price %></p>
    <% end %>
    <% if @tender.is_completed? %><div class="seal"><%= image_tag("seal_done_sm.png", alt: "", width: "100%")%></div><% end %>
  </div>
  <div class="time bfR"><%= @tender.created_at.strftime("%Y/%m/%d %H:%M")%></div>
</div>
<%- unless [nil, ''].include?(@tender.remark) %>
  <div class="remark">
    <div class="tt bfL">报价备注：</div>
    <div class="info"><%= @tender.remark%></div>
  </div>
<% end %>
<%= link_to '成交', complete_post_path(@post, tender_id: @tender.id), method: 'put', class: 'btn btn-default btnW200 btn_spacing mt20 orange sub' if current_user == @post.user && @post.status != 3 %>
<!--<%#= render 'comment_form'%>-->

app/views/posts/index.html.erb
<%= render partial: "list_#{@_type}" %>

app/views/posts/user_list.html.erb
<%= render partial: "user_list_#{@_type}" %>