config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :log_user_update_levels do
      member do
        patch :update_status
      end
    end
    
    resources :feedbacks, only: [:index] do
    end

    resources :users do
      collection do
        get :search
        get :contacted
        get :registered
        post :contact
        post :set_staff
        get :staff_list
      end
      member do
        get :edit_staff
        patch :update_staff
        get :update_remark
        get :update_status
        patch :update_role
        get :update_user_remark
      end
    end

    resources :banners
    resources :posts do
      collection do
        get :resources_list
        get :hot_resources
      end
      member do
        put :update_sys
        put :approve_base_car
      end
    end
    resources :helpers, except: [ :show ]

    resources :messages, only: [:index, :new, :create, :destroy]
    root 'users#search'
    resources :base_cars do
      member do
        get :update_status
      end
      collection do
        get :st_list
        get :br_list
        get :cm_list
        get :get_select_infos
        get :get_cm_select_infos
        get :new_cm
        get :new_br
        get :new_st
        get :edit_cm
        get :edit_br
        get :edit_st
        post :create_cm
        post :create_br
        post :create_st
        put :update_br
        put :update_st
        patch :update_cm
      end
    end
    resources :complaints, only: [:index, :update]
  end

  root 'portal#index'

  devise_for :users, controllers: {
                                    sessions:      'users/sessions',
                                    confirmations: 'users/confirmations',
                                    registrations: 'users/registrations',
                                    passwords:     'users/passwords',
                                    unlocks:       'users/unlocks'
                                  }

  namespace :users do
    resources :messages do
    end
  end

  resources :users, only: [ :show, :edit, :update ] do
    member do
      get :my_tenders
      get :my_followers
      get :system_infos
      get :my_level
      get :edit_my_level
      put :update_my_level
      get :about_us
    end
    patch :add_following, on: :collection

    get :delete_relation, on: :collection

    patch :reset_password, on: :collection

    get :user_protocel, on: :collection

    resources :my_posts do
      member do
        patch :update
      end
      collection do
        get :get_select_infos
        post :update_position
      end
      resources :tenders, only: [ :show ]
    end
  end

  resources :posts do
    collection do
      get :resources_list
      get :needs_list
      get :user_list
      get :user_resources_list
      get :download_posts
      get :key_search
    end
    member do
      post :tender
      put  :complete
      get  :my_tender
      get  :his_tender
    end
  end

  resources :follow_ships, only: [ :create, :destroy ]

  resources :valid_codes, only: [ :create ] do
    get :_valid, on: :collection
  end

  resources :photos, only: [ :index ] do
    post :upload, on: :collection
  end

  resources :areas, only: [:show]
  resources :complaints, only: [ :create ]
  resources :comments, only: [ :create ]

  resources :helpers, only: [ :index, :show ]

  resources :mobile_displays, only: [:index]

  namespace :api, :defaults => { :format => 'json' } do
    devise_scope :user do
      post    'sessions'      => 'sessions#create',       :as => 'login'
      delete  'sessions'      => 'sessions#destroy',      :as => 'logout'
      post    'registrations' => 'registrations#create',  :as => 'register'
    end

    resources :banners, only: [:index]
    resources :helpers, only: [ :index, :show ]

    resources :messages do
      post :device_methods, on: :collection
      post :update_messages, on: :collection
      post :destroy_messages, on: :collection
    end

    resources :base_cars, only: [:index]

    namespace :posts do
      get   :list
      get   :my_list
      get   :my_tenders
      get   :user_list
      get   :show
      post  :create
      post  :tender
      put   :complete
      post  :update_all
      put  :change_position
      delete :destroy
      put :del_my_tender
      get :search
      get :tender_status
      get :filter_brands
      get :filter_brand
      post :gen_log
    end

    resources :valid_codes, only: [:index] do
      get :validate_code, on: :collection
    end

    resources :areas, only: [:index] do
    end

    namespace :follow_ships do
      get   :my_followers
      get   :my_followings
      get   :joint_followers
      get   :joint_followings
      post  :create
      put   :unfollow
    end

    namespace :complaints do
      post :create
    end

    namespace :comments do
      get  :list
      post :create
      post :reply
    end

    namespace :users do
      get :list
      get :has_updated
      post :update_level
      patch :change_password
      patch :reset_password
      put   :update
      get :show
      get :check_unread
      get :customer_service
    end

    resources :phone_lists, only: [:index] do
      post :contact_list, on: :collection
      get :send_invite_message, on: :collection
    end
  end

  # mount RailsAdmin::Engine => '/a', as: 'rails_admin'

end

app/controllers/admin/users_controller.rb
# encoding: utf-8
class Admin::UsersController < Admin::BaseController
  before_filter :require_super_admin, only: [:staff_list]

  def search
    @mobile_log = Log::ContactPhone.find_or_initialize_by(mobile: params[:mobile])

    respond_to do |format|
      format.html
      format.js { render :layout => false }
    end
  end

  def contacted
    # TODO: Add logic for contacted users 已联系用户
    conds = {_type: 0, is_register: false}
    conds[:sender_id] = current_staff.id if staff?
    conds[:mobile] = params[:mobile] if params[:mobile].present?
    @mobiles = Log::ContactPhone.where(conds).order('updated_at desc').page(params[:page]||1).per(30)
    @show_datas = staff? ?  [
                              current_staff.log_contact_phones.today.count,
                              current_staff.log_contact_phones.month.count,
                              current_staff.log_contact_phones.count
                            ] : [
                              Log::ContactPhone.today.count,
                              Log::ContactPhone.month.count,
                              Log::ContactPhone.count
                            ]
  end

  def registered
    # TODO: Add logic for registered users 已注册用户
    
    if params[:sort_way]
      @sort = params[:sort_way] != 'created_at' ? "#{params[:sort_way]} asc" : 'created_at desc' 
    else
      @sort = 'created_at desc'
    end
    
    @sort_way = params[:sort_way] || 'created_at'
    
    @users =  if staff?
                current_staff.customers.order(@sort).page(params[:page]||1).per(30)
              else
                 User.where("customer_service_id is not NULL").order(@sort).page(params[:page]||1).per(30)
              end
              
    
    @users = @users.where(mobile: params[:mobile]) if params[:mobile].present?
              
    @show_datas = staff? ?  [
                              current_staff.customers.today.count,
                              current_staff.customers.month.count,
                              current_staff.customers.count
                            ] : [
                              User.where("customer_service_id is not NULL").today.count,
                              User.where("customer_service_id is not NULL").month.count,
                              User.where("customer_service_id is not NULL").count
                            ]
  end

  def new
    user_hash = if params[:mask] == 'Staff'
                  {
                    mask: 'Staff',
                    contact: {
                      wx:              nil,
                      qq:              nil,
                      remark:          nil,
                      company_address: nil,
                      phone:           nil,
                      web_site:        nil,
                      company_email:   nil
                    }
                  }
                else
                  params.require(:user).permit!
                  params[:user].merge(
                    contact:  {
                                company_address:    nil,
                                position_header:    nil,
                                wx:                 nil,
                                qq:                 nil,
                                self_introduction:  nil
                  })
                end
    @user = User.new(user_hash)
  end

  def create
    if params[:staff]
      params.require(:staff).permit!
      @user = Staff.new(params[:staff])
      @user.role = 'staff'
    else
      params.require(:user).permit!
      @user = User.new(params[:user])
    end
    
    if params[:_image].present?
      avatar = @user.photos.where(_type: 'avatar').first_or_initialize 
      avatar.image = params[:_image]
      avatar._type = 'avatar'
      avatar.save
    end

    if @user.save
      if @user.mask.nil?
        log = Log::ContactPhone.where(mobile: @user.mobile).first_or_initialize
        log.is_register = true
        log._type = 0
        log.reg_admin = @current_staff
        log.save
        @user.contact[:remark] = log.remark
        @user.save
        redirect_to registered_admin_users_path
      else
        redirect_to staff_list_admin_users_path
      end
    else
      logger.info "errors message:" + @user.errors.full_messages.join('\n')
      render :new
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
    if @user.blank?
      redirect_to :back, notice: '很抱歉，此用户不存在'
    end
  end

  def update
    @user = User.find_by_id(params[:id])
    
    if params[:_image].present?
      avatar = @user.photos.where(_type: 'avatar').first_or_initialize 
      avatar.image = params[:_image]
      avatar._type = 'avatar'
      avatar.save
    end
    
    if @user.mask.blank? or @user.mask != 'Staff'
      params.require(:user).permit!
      @user.update_attributes(params[:user])
      
      redirect_to registered_admin_users_path
    else
      params.require(:staff).permit!
      @user.update_attributes(params[:staff])

      redirect_to staff_list_admin_users_path
    end
  end

  # 我来联系, 归入自己的通讯录
  def contact
    @contact_phone = Log::ContactPhone.new(
                mobile: params[:mobile],
                sender_id: current_staff.id
              )
    if @contact_phone.save
      redirect_to contacted_admin_users_path, notice: '已加入通讯录'
    else
      flash[:alert] = @contact_phone.errors.full_messages.join(', ')
      redirect_to search_admin_users_path(mobile: params[:mobile])
    end
  end

  # 指定业务员
  def set_staff
    @contact_phone = Log::ContactPhone.new(
                mobile: params[:mobile],
                sender_id: params[:staff_id]
              )
    if @contact_phone.save
      redirect_to contacted_admin_users_path, notice: '已加入通讯录'
    else
      flash[:alert] = @contact_phone.errors.full_messages.join(', ')
      redirect_to search_admin_users_path(mobile: params[:mobile])
    end
  end

  def index
    @mobile = params[:mobile] && params[:mobile] != "" ? params[:mobile] : nil
    @level  = params[:level] && params[:level]!= "" ? params[:level] : nil

    conds = {role: 'normal'}
    conds[:mobile] = @mobile if @mobile
    conds[:level]  = @level  if @level

    @users = User.where(conds).includes(:customer_service).order(created_at: :desc).page(params[:page]||1).per(30)
  end

  def staff_list
    @staffs = Staff.order(created_at: :desc).page(params[:page]||1).per(30)
  end

  def edit_staff
    @user = User.find_by_id(params[:id])
  end

  def update_staff
    @user = User.find_by_id(params[:id])

    params.require(:user).permit!

    @user.update_attributes(params[:user])

    redirect_to staff_list_admin_users_path
  end

  def update_remark
    mobile = Log::ContactPhone.find_by_id(params[:id])
    mobile.remark = params[:remark]
    mobile.save

    redirect_to :back
  end

  def update_status
    user = User.find_by_id(params[:id])
    user.update_attributes(status: params[:status].to_i)

    redirect_to :back
  end

  def update_role
    staff = Staff.find_by_id(params[:id])
    staff.update_attributes(role: params[:role])

    redirect_to :back
  end
  
  def update_user_remark
    user = User.find params[:id]
    user.contact[:remark] = params[:remark]
    user.save
     
    redirect_to :back
  end

end

app/controllers/users/confirmations_controller.rb
# encoding: utf-8

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/messages_controller.rb
# encoding: utf-8

class Users::MessagesController < BaseController
  
  def index
    @send_messages = current_user.send_feedbacks
    @received_message = current_user.received_feedbacks
  end
  
  def create
    @fb = Feedback.new message_params
    if @fb.save
      flash[:notice] = t('success')
      redirect_to my_level_user_path(current_user)
    else
      flash[:error] = t('failed')
      redirect_to :back
    end
  end
  
  def show
    @message = Message.find params[:id]
  end
  
  private
  def message_params
    params.require(:feedback).permit(:sender_id, :receiver_id, :title, :content, :_type)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# encoding: utf-8

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# encoding: utf-8

class Users::PasswordsController < Devise::PasswordsController
  
  before_filter :require_no_authentication, except: [:edit, :update]
  before_filter :assert_reset_token_passed, except: [:edit, :update]
  
  before_filter :configure_sign_in_params, only: [:update, :create]

  skip_before_action :assert_reset_token_passed, only: [ :new, :create ]

  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    
    params_container = resource_name == :user ? user_params : params[resource_name]
    
    if resource.update_with_password(params_container)
      set_flash_message :notice, :updated if is_navigational_format?
      sign_in resource_name, resource, :bypass => true
      respond_with resource, :location => after_update_path_for(resource)
      flash[:notice] = '修改密码成功！'
    else
      clean_up_passwords(resource)
      #respond_with_navigational(resource){ render_with_scope :edit }
      flash[:notice] = '修改密码未能成功！请检查是否原密码正确或是两次输入新密码不一致'
      redirect_to :back
    end
        
  end
  
  protected
  # You can put the params you want to permit in the empty array.
  def configure_sign_in_params
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:current_user, :password, :password_confirmation ) }
  end

  def after_update_path_for(resource)
    #super(resource)
    request.referrer || '/'
  end
  
  def user_params
    params[:user].permit(:current_password, :password, :password_confirmation)
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user_helper.rb
# encoding: utf-8

module UserHelper
  
  def user_level_icons(user)
   list = case user.level
          when User::LEVELS.keys[0] then
            %w(user/typeIcon_p_dis.png user/typeIcon_s_dis.png user/typeIcon_z_dis.png)
          when User::LEVELS.keys[1] then
            %w(user/typeIcon_p.png user/typeIcon_s_dis.png user/typeIcon_z_dis.png)
          when User::LEVELS.keys[2] then
            %w(user/typeIcon_p.png user/typeIcon_s.png user/typeIcon_z_dis.png)
          else
            %w(user/typeIcon_p.png user/typeIcon_s.png user/typeIcon_z.png)
          end 
    #list.unshift('user/typeIcon_p.png')      
    list
  end
  
  def recon_icons(user)
    if user.level == User::LEVELS.keys[4]
      %w(user/typeIcon_4s.png)                                                         
    else
      %w(user/typeIcon_4s_dis.png)
    end 
  end

end

app/views/admin/users/_form.haml
= form_for(@user, url: @user.new_record? ? admin_users_path : admin_user_path,  html: { multipart: true }) do |f|
  .form-group.clearfix
    = f.label '姓名'
    = f.text_field :name, class: "form-control"
  .form-group.clearfix
    = f.label '手机号'
    = f.text_field :mobile, class: "form-control", readonly: "readonly"
  / .form-group.clearfix
  /   = f.label '密码'
  /   = f.password_field :password, class: "form-control"
  .form-group.clearfix
    = f.label '注册地'
    = select_tag 'province', options_for_select(areas(level: :provinces)), id: 'province', class: "form-control", prompt: '请选择省份'
    = f.select :area_id, options_for_select([[@user.area.try(:name), @user.area.try(:id)]], selected: @user.area_id), {prompt: '请选择城市'}, {id: 'city', class: "form-control"}
  .form-group.clearfix
    = f.label '公司'
    = f.text_field :company, class: "form-control"

  = f.fields_for :contact do |c_f|
    .form-group.clearfix
      = c_f.label '公司地址'
      = c_f.text_field :company_address, class: "form-control", value: @user.contact['company_address']
    .form-group.clearfix
      = c_f.label '职业'
      = c_f.text_field :position_header, class: "form-control", value: @user.contact['position_header']
    .form-group.clearfix
      = c_f.label '微信'
      = c_f.text_field :wx, class: "form-control", value: @user.contact['wx']
      .form-group.clearfix
      = c_f.label 'QQ'
      = c_f.text_field :qq, class: "form-control", value: @user.contact['qq']
    .form-group.clearfix
      = c_f.label '自我简介'
      = c_f.text_area :self_introduction, class: "form-control w100p", row: "4", value: @user.contact['self_introduction']

  .form-group.clearfix
    = f.label '指定业务员'
    = f.collection_select :customer_service_id, Staff.customer_services, :id, :name, prompt: true
    
  .form-group.clearfix
    .col-md-3.photoArea
      .photo.show-img
        = image_tag(@user.avatar, alt: "", width: "180", height: "180", id: 'show-img')
      
      = label_tag '修改头像'
      %br
      = file_field_tag :_image, value: @user.avatar, type: :file, multiple: true, class: 'button', accept: 'image/png,image/gif,image/jpeg, image/jpg', 'target-id' => 'show-img'
      = hidden_field_tag :_type, 'avatar' 
    
  = f.hidden_field :reg_status, value: '3'
  = f.hidden_field :role, value: 'normal'
  = f.hidden_field :status, value: 1
  = f.hidden_field :password, value: '123456' if @user.new_record?
  .form-group.clearfix
    = f.submit class: "btn btn-default subBtn"

= javascript_include_tag "edit_user"

app/views/admin/users/_search_result.haml
.hr-line-dashed
.search-result.clearfix
  - if @mobile_log.new_record?
    - if admin? || super_admin?
      .dropdown.bfL
        %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "data-toggle" => "dropdown", :type => "button", "aria-expanded" => "false"}
          指定业务员
          %span.caret
        %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1", :role => "menu", "aria-labelledby" => "dLabel"}
          - Staff.customer_services.each do |staff|
            %li{:role => "presentation"}
              = link_to staff.name, set_staff_admin_users_path(mobile: @mobile_log.mobile, staff_id: staff.id), method: :post, role: "menuitem", tabindex: "-1"
    - else
      = link_to '我来联系', contact_admin_users_path(mobile: @mobile_log.mobile), method: :post, class: 'btn btn-warning bfL'

    = link_to '取消', search_admin_users_path, class: 'btn bfL'
  - else
    - if @mobile_log.is_register
      - if staff?
        = "已注册，用户名为#{@mobile_log.user.name}"
      - else
        = link_to "已注册，用户名为#{@mobile_log.user.name}, 点击详情", user_list_posts_path(user_id: @mobile_log.user.id, _type: 0), target: '_blank'
    - elsif @mobile_log.contacted?
      = "已由#{@mobile_log.sender.job_number}已联系"

app/views/admin/users/_staff_form.haml
= form_for(@user, url: @user.new_record? ? admin_users_path : admin_user_path, html: { multipart: true }) do |f|

  = f.hidden_field :mask, value: @user.mask
  = f.hidden_field :status, value: 1
  = f.hidden_field :password, value: '123456' if @user.new_record?
  
  .form-group.clearfix
    = f.label '姓名'
    = f.text_field :name, class: "form-control"
  .form-group.clearfix
    = f.label '手机号'
    = f.text_field :mobile, class: "form-control"
  .form-group.clearfix
    = f.label '工号'
    = f.text_field :job_number, class: "form-control"
  / .form-group.clearfix
  /   = f.label '密码'
  /   = f.password_field :password, class: "form-control"
  .form-group.clearfix
    = f.label '注册地'
    = select_tag 'province', options_for_select(areas(level: :provinces)), id: 'province', class: "form-control", prompt: '请选择省份'
    = f.select :area_id, options_for_select([[@user.area.try(:name), @user.area.try(:id)]], selected: @user.area_id), {prompt: '请选择城市'}, {id: 'city', class: "form-control"}
  .form-group.clearfix
    = f.label '公司'
    = f.text_field :company, class: "form-control"

  = f.fields_for :contact do |c_f|
    .form-group.clearfix
      = c_f.label '微信'
      = c_f.text_field :wx, class: "form-control", value: @user.contact['wx']
    .form-group.clearfix
      = c_f.label 'QQ'
      = c_f.text_field :qq, class: "form-control", value: @user.contact['qq']
    .form-group.clearfix
      = c_f.label '电话'
      = c_f.text_field :phone, class: "form-control", value: @user.contact['phone']
    .form-group.clearfix
      = c_f.label '公司地址'
      = c_f.text_field :company_address, class: "form-control", value: @user.contact['company_address']
    .form-group.clearfix
      = c_f.label '公司邮箱'
      = c_f.text_field :company_email, class: "form-control", value: @user.contact['company_email']
    .form-group.clearfix
      = c_f.label '公司网站'
      = c_f.text_field :web_site, class: "form-control", value: @user.contact['web_site']
    .form-group.clearfix
      = c_f.label '备注'
      = c_f.text_area :remark, class: "form-control w100p", row: "4", value: @user.contact['remark']
    
  .form-group.clearfix
    .col-md-3.photoArea
      .photo.show-img
        = image_tag(@user.avatar, alt: "", width: "180", height: "180", id: 'show-img')
  
      = label_tag '修改头像'
      %br
      = file_field_tag :_image, value: @user.avatar, type: :file, multiple: true, class: 'button', accept: 'image/png,image/gif,image/jpeg, image/jpg', 'target-id' => 'show-img'
      = hidden_field_tag :_type, 'avatar'  

  / .form-group.clearfix
  /   = f.label '分配角色'
  /   = f.select :role, Staff::ROLES[0, 2], prompt: true
  .form-group.clearfix
    = f.submit class: "btn btn-default subBtn"

= javascript_include_tag "edit_user"

app/views/admin/users/edit.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-9
    %h2 编辑

.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          = render @user.mask == 'Staff' ? 'staff_form' : 'form'

app/views/admin/users/edit_staff.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-9
    %h2 编辑角色

.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          = form_for(@user, url: update_staff_admin_user_path) do |f|
            .form-group.clearfix
              = f.label '工号'
              = f.text_field :job_number, class: "form-control"
            .form-group.clearfix
              = f.label '分配角色'
              = f.select :role, Staff::ROLES[0, 2], prompt: true

            = f.hidden_field :mask, value: 'Staff'

            .form-group.clearfix
              = f.submit class: "btn btn-default subBtn"

app/views/admin/users/index.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-9
    %h2 用户列表

.wrapper.wrapper-content.animated.fadeInRight

  .ibox.float-e-margins
    .ibox-content
      .row
        .col-lg-12.searchTag
          = form_tag params, action: 'index', method: :get, class: 'form-horizontal' do
            .col-md-6
              = text_field_tag :mobile, @mobile, type: 'mobile', class: 'form-control input-lg', placeholder: '输入手机号码'
            .col-md-4
              = select_tag(:level, options_for_select(User::LEVELS.collect{|ele| [ele[1], ele[0]]}, @level), class: "form-control input-lg", prompt: "请选择等级")
            .col-md-2
              %button.btn.btn-lg.btn-primary{ type: 'submit'} 查询
        .col-lg-12
          %table.table.table-striped
            %tr
              %th 序号
              %th 业务员工号
              %th 姓名
              %th 状态
              %th 联系电话
              %th{ style: 'width: 120px;'} 公司名称
              %th 认证等级
              %th 注册日期
              %th 最后一次登录时间
              %th 成交记录
              %th 操作
            - @users.each do |user|
              %tr
                %td= user.id
                %td= user.customer_service.try(:job_number)
                %td
                  = link_to user.name, user_list_posts_path(user_id: user.id, _type: 0), target: '_blank'
                %td= User::STATUS[user.status]
                %td= user.mobile
                %td= user.company
                %td= User::LEVELS[user.level]
                %td= user.created_at.strftime("%Y-%m-%d %H:%M")
                %td= user.last_sign_in_at.strftime("%Y-%m-%d %H:%M") if user.last_sign_in_at
                %td= user.dealt_infos
                %td
                  = link_to '修改', edit_admin_user_path(user)
                  - if user.is_valid
                    = link_to '关闭', update_status_admin_user_path(user, status: -1)
                  - else
                    = link_to '恢复', update_status_admin_user_path(user, status: 1)
                  = link_to '修改角色', edit_staff_admin_user_path(user)

        .col-lg-12
          - if @users.present?
            .hr-line-dashed

          .text-center
            = paginate @users

app/views/admin/users/new.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-9
    %h2 注册

.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox.float-e-margins
        .ibox-content
          = render @user.mask == 'Staff' ? 'staff_form' : 'form'

app/views/admin/users/search.js.erb
$('.search-result-wrapper').html("<%= escape_javascript(render 'search_result') %>")

app/views/admin/users/staff_list.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-9
    %h2 内部员工列表

.wrapper.wrapper-content.animated.fadeInRight
  = link_to '新建员工', new_admin_user_path(mask: 'Staff')
  .ibox.float-e-margins
    .ibox-content
      .row
        .col-lg-12
          %table.table.table-striped.listTable
            %tr
              %th 序号
              %th 工号
              %th 角色
              %th 姓名
              %th 联系电话
              %th 状态
              %th 操作
            - @staffs.each do |staff|
              %tr
                %td= staff.id
                %td= staff.job_number
                %td
                  - if staff.role == 'super_admin'
                    = staff.role
                  - else
                    = form_for staff, url: update_role_admin_user_path(staff), method: 'patch' do |f|
                      .row.tabSelect
                        .col-sm-8
                          = select_tag(:role, options_for_select([['staff', 'staff'], ['admin', 'admin']]), class: "form-control input-sm", prompt: staff.role)
                        .col-sm-4
                          = f.submit:'确认', class: 'btn btn-primary btn-sm'
                %td= staff.name
                %td= staff.mobile
                %td= staff.is_valid ? '正常' : '已关闭'
                %td
                  = link_to '修改', edit_admin_user_path(staff)
                  - unless staff.role == 'super_admin'
                    - if staff.is_valid
                      = link_to '关闭', update_status_admin_user_path(staff, status: -1)
                    - else
                      = link_to '恢复', update_status_admin_user_path(staff, status: 1)

        .col-lg-12
          - if @staffs.present?
            .hr-line-dashed

          .text-center
            = paginate @staffs